const sidebars = {
  tutorialSidebar: [
    'tutorials/intro',
    'teszt-doku',
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [
        'tutorials/tutorial-basics/congratulations',
        'tutorials/tutorial-basics/create-a-blog-post',
        'tutorials/tutorial-basics/create-a-document',
        'tutorials/tutorial-basics/deploy-your-site',
        'tutorials/tutorial-basics/markdown-features',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [
        'tutorials/tutorial-extras/manage-docs-versions',
        'tutorials/tutorial-extras/translate-your-site',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
  ],
};

export default sidebars;
