// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Alapértelmezett automatikus oldalsáv a docs mappához
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Hivatkozás az OpenAPI plugin által generált oldalsáv fájlra
  myApiSidebar: require('./docs/petstore/sidebar.ts'),
};

export default sidebars;
